# Generated by Django 3.2.7 on 2021-11-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['short_name', '-update_at', '-create_at'], 'verbose_name': '題目', 'verbose_name_plural': '題目'},
        ),
        migrations.AddField(
            model_name='probleminout',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='是否為範例測資'),
        ),
    ]
