# Generated by Django 3.2.19 on 2023-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20211129_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='是否上傳'),
        ),
    ]
