# Generated by Django 3.2.19 on 2023-09-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domservers', '0002_alter_domserverclient_mask_password'),
        ('problems', '0003_problem_is_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_problem_id', models.CharField(max_length=68, verbose_name='網站題目ID')),
                ('web_problem_contest', models.CharField(max_length=68, verbose_name='網站比賽區號')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_log', to='problems.problem')),
                ('server_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domservers.domserverclient')),
            ],
        ),
    ]
