# Generated by Django 3.2.19 on 2023-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problemserverlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='web_problem_id',
            field=models.CharField(blank=True, max_length=68, null=True, verbose_name='網站題目ID'),
        ),
    ]
