# Generated by Django 3.2.19 on 2023-09-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_web_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='題目名稱'),
        ),
    ]
