# Generated by Django 3.2.19 on 2023-09-13 12:03

import app.problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=255, validators=[app.problems.models.validate_problem_name], verbose_name='題目名稱'),
        ),
    ]
