# Generated by Django 3.2.19 on 2023-11-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemserverlog',
            name='web_problem_contest',
            field=models.CharField(blank=True, max_length=68, null=True, verbose_name='網站比賽區號'),
        ),
    ]
