# Generated by Django 3.2.19 on 2023-11-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_alter_problemserverlog_web_problem_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemserverlog',
            name='web_problem_state',
            field=models.CharField(choices=[('新增', '新增'), ('移除', '移除')], default='新增', max_length=2, verbose_name='存放狀態'),
        ),
        migrations.AlterField(
            model_name='problemserverlog',
            name='web_problem_contest',
            field=models.CharField(max_length=68, verbose_name='網站比賽區號'),
        ),
    ]
