# Generated by Django 3.2.23 on 2024-02-13 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domservers', '0004_contestrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0010_auto_20231118_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemserverlog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_log', to=settings.AUTH_USER_MODEL, verbose_name='使用者紀錄'),
        ),
        migrations.AlterField(
            model_name='problemserverlog',
            name='problem',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='problem_log', to='problems.problem', verbose_name='題目紀錄'),
        ),
        migrations.AlterField(
            model_name='problemserverlog',
            name='server_client',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='server_log', to='domservers.domserverclient', verbose_name='伺服器紀錄'),
        ),
    ]
