# Generated by Django 3.2.23 on 2024-02-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domservers', '0005_rename_user_contestrecord_owner'),
        ('problems', '0012_alter_problemserverlog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemserverlog',
            name='web_problem_contest',
        ),
        migrations.AddField(
            model_name='problemserverlog',
            name='web_problem_contest_cid',
            field=models.CharField(default=1, max_length=68, verbose_name='網站競賽區CID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problemserverlog',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_log', to='problems.problem', verbose_name='題目紀錄'),
        ),
        migrations.AlterField(
            model_name='problemserverlog',
            name='server_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_log', to='domservers.domserverclient', verbose_name='伺服器紀錄'),
        ),
    ]
