# Generated by Django 3.2.23 on 2024-04-23 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('domservers', '0001_initial'), ('domservers', '0002_alter_domserverclient_mask_password'), ('domservers', '0003_alter_domserverclient_mask_password'), ('domservers', '0004_contestrecord'), ('domservers', '0005_rename_user_contestrecord_owner'), ('domservers', '0006_alter_domserverclient_name'), ('domservers', '0007_rename_domjudge_contest_id_contestrecord_cid'), ('domservers', '0008_auto_20240401_1556'), ('domservers', '0009_alter_domservercontest_options')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomServerClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='主機名稱')),
                ('host', models.URLField(help_text='https://domserver.example.com', verbose_name='Dom server URL')),
                ('disable_ssl', models.BooleanField(default=False)),
                ('timeout', models.BooleanField(default=False)),
                ('version', models.CharField(default='7.3.2', max_length=16, verbose_name='Dom Server 版本')),
                ('api_version', models.CharField(default='v4', max_length=16, verbose_name='Dom Server API 版本')),
            ],
            options={
                'verbose_name': 'Dom Server 內容資訊',
                'verbose_name_plural': 'Dom Server 內容資訊',
            },
        ),
        migrations.CreateModel(
            name='DomServerUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('username', models.CharField(help_text='必須要有 "API reader", "API writer" roles', max_length=128, verbose_name='帳號')),
                ('mask_password', django_cryptography.fields.encrypt(models.CharField(max_length=128, verbose_name='密碼'))),
                ('category_id', models.BigIntegerField(default=0, help_text='請輸入類型ID', verbose_name='類型ID')),
                ('affiliation_id', models.BigIntegerField(default=0, help_text='請輸入所屬關係ID', verbose_name='所屬關係ID')),
                ('affiliation_country', models.CharField(default='TWN', max_length=128, verbose_name='所屬國家')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('server_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_client', to='domservers.domserverclient', verbose_name='伺服器')),
            ],
            options={
                'verbose_name': 'Dom Server 連線資訊',
                'verbose_name_plural': 'Dom Server 連線資訊',
            },
        ),
        migrations.CreateModel(
            name='DomServerContest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('cid', models.CharField(editable=False, max_length=255, verbose_name='考區ID')),
                ('name', models.CharField(max_length=255, verbose_name='考區名稱')),
                ('short_name', models.CharField(max_length=255, verbose_name='考區簡稱')),
                ('start_time', models.CharField(max_length=255, verbose_name='開始時間')),
                ('end_time', models.CharField(max_length=255, verbose_name='記分牌結束時間')),
                ('activate_time', models.CharField(max_length=255, verbose_name='啟動時間')),
                ('scoreboard_freeze_length', models.CharField(blank=True, max_length=255, null=True, verbose_name='凍結時間')),
                ('scoreboard_unfreeze_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='記分牌解凍時間')),
                ('deactivate_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='停用時間')),
                ('start_time_enabled', models.BooleanField(default=False, verbose_name='是否啟用開始時間')),
                ('process_balloons', models.BooleanField(default=False, verbose_name='是否啟用處理氣球')),
                ('open_to_all_teams', models.BooleanField(default=False, verbose_name='是否向所有團隊開放')),
                ('contest_visible_on_public_scoreboard', models.BooleanField(default=False, verbose_name='是否比賽在公共計分板上可見')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否啟用')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_owner', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('server_client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contest_server_client', to='domservers.domserverclient', verbose_name='伺服器紀錄')),
            ],
            options={
                'verbose_name': 'DomServer Contest 考場',
                'verbose_name_plural': 'DomServer Contest 考場',
            },
        ),
        migrations.AddConstraint(
            model_name='domservercontest',
            constraint=models.UniqueConstraint(fields=('server_client', 'cid'), name='unique_server_client_cid'),
        ),
        migrations.AlterModelOptions(
            name='domservercontest',
            options={'verbose_name': 'DomServer Contest 考區', 'verbose_name_plural': 'DomServer Contest 考區'},
        ),
    ]
