# Generated by Django 3.2.19 on 2023-08-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domservers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domserverclient',
            name='mask_password',
            field=models.CharField(max_length=128, verbose_name='密碼'),
        ),
    ]
