# Generated by Django 3.2.19 on 2023-09-13 09:47

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domservers', '0002_alter_domserverclient_mask_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domserverclient',
            name='mask_password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=128, verbose_name='密碼')),
        ),
    ]
