# Generated by Django 3.2.23 on 2024-02-13 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domservers', '0003_alter_domserverclient_mask_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('server_id', models.TextField(editable=False, help_text='請輸入伺服器ID', verbose_name='伺服器ID')),
                ('domjudge_contest_id', models.TextField(editable=False, help_text='請輸入Domjudge考區ID', verbose_name='Domjudge考區ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_records', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'Contest 紀錄',
                'verbose_name_plural': 'Contest 紀錄',
            },
        ),
    ]
