# Generated by Django 3.2.23 on 2024-02-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domservers', '0004_contestrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestrecord',
            old_name='user',
            new_name='owner',
        ),
    ]
