# Generated by Django 3.2.23 on 2024-02-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domservers', '0006_alter_domserverclient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestrecord',
            old_name='domjudge_contest_id',
            new_name='cid',
        ),
    ]
