# Generated by Django 3.2.23 on 2024-04-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domservers', '0008_auto_20240401_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domservercontest',
            options={'verbose_name': 'DomServer Contest 考區', 'verbose_name_plural': 'DomServer Contest 考區'},
        ),
    ]
